services:
  prospectio-api-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prospectio-api-mcp
    ports:
      - "7002:7002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7002/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - prospectio
    env_file:
      - .env.docker
    depends_on:
      prospectio-api-mcp-db:
        condition: service_healthy

  prospectio-api-mcp-db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: prospectio-api-mcp-pgvector
    environment:
      POSTGRES_USER: prospectio
      POSTGRES_PASSWORD: prospectio
      POSTGRES_DB: prospectio
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prospectio -d prospectio"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prospectio

networks:
  prospectio:
    external: true