[tool.poetry]
name = "prospectio-mcp-api"
version = "0.1.0"
description = "Prospectio MCP API"
authors = ["Yohan Goncalves <yohan.goncalves.pro@gmail.com>"]
license = "Apache 2.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12.7"
pydantic = "2.10.3"
httpx = "0.28.1"
mcp = "1.10.1"
fastapi = { version = "0.115.14", extras = ["standard"]}

[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
