curl --request POST \
  --url 'http://localhost:7002/prospectio/rest/v1/insert/leads' \
  --header 'Accept: application/json, text/event-stream' \
  --header 'Content-Type: application/json' \
  --data '{"source": "jsearch","location": "France","job_title": ["Python","Fastapi"]}'
###

curl --request GET \
  --url 'http://localhost:7002/prospectio/rest/v1/leads/jobs/0' \
  --header 'Accept: application/json, text/event-stream'
  
###

curl --request GET \
  --url 'http://localhost:7002/prospectio/rest/v1/profile' \
  --header 'Accept: application/json, text/event-stream'

###

curl --request POST \
  --url http://localhost:7002/prospectio/rest/v1/profile/upsert \
  --header 'Content-Type: application/json' \
  --data '{
	"job_title": "Software Developer",
	"location": "FR",
	"bio": "Passionate developer",
	"work_experience": [
		{
			"company": "TechCorp",
			"position": "Developer",
			"start_date": "2020-01",
			"end_date": "2023-12",
			"description": "Full-stack development"
		}
	]
}'





