curl --request GET \
  --url 'http://localhost:7002/rest/v1/company/jobs/jsearch?job_title=python&location=france' \
  --header 'Accept: application/json, text/event-stream'

###

curl --request GET \
  --url 'http://localhost:7002/rest/v1/company/jobs/active_jobs_db?job_title=python&location=france' \
  --header 'Accept: application/json, text/event-stream'